# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20171013_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('E-book', 'E-book')], max_length=120),
        ),
    ]
